# Ticket classification

## Starting

Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

Call your data

In [2]:
#data = pd.read_csv('generated_tickets_csv.csv')
data = pd.read_csv('./Tickets data collection.csv')
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Timestamp              167 non-null    str
 1   Title of your ticket   193 non-null    str
 2   Write your ticket      194 non-null    str
 3   Your ticket is about:  195 non-null    str
dtypes: str(4)
memory usage: 6.2 KB
None

Check your data

What do you think we really need to use in our model?

In [3]:
data

,Timestamp,Title of your ticket,Write your ticket,Your ticket is about:
0,2023/10/10 12:36:43 pm EEST,Employee Data Access Request,An employee has requested access to their pers...,Privacy issue
1,2023/10/10 12:37:18 pm EEST,Request for New Monitors,We need to purchase 10 new high-resolution mon...,Purchase requisition
2,2023/10/10 1:51:10 pm EEST,Email Client Crashing,Our email client is frequently crashing on sta...,Software issue
3,2023/10/10 1:51:44 pm EEST,Slow File-Sharing Server,The company's file-sharing server is experienc...,Software issue
4,2023/10/10 1:52:43 pm EEST,Software License Procurement,We need to purchase a new software license for...,Purchase requisition
...,...,...,...,...
190,NaN,Customer Data Deletion Request,NaN,Privacy issue
191,NaN,Privacy Policy Update,Our privacy policy needs to be updated to refl...,Privacy issue
192,NaN,Vendor Data Handling Assessment,Assess how our vendors handle our data and ens...,Privacy issue
193,NaN,Privacy Impact Assessment,Conduct a Privacy Impact Assessment (PIA) for ...,Privacy issue
194,NaN,Incident Response Plan Review,Review and update our privacy incident respons...,Privacy issue

In [12]:
# Change the name of the columns to: Timestam, Title, Description and Class
data
data.rename(columns={'Title of your ticket': 'Title', 'Write your ticket': 'Description', 'Your ticket is about': 'About'}, inplace=True)
data.drop(columns='Timestamp', inplace=True)
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  195 non-null    str
 1   Description            194 non-null    str
 2   Your ticket is about:  195 non-null    str
dtypes: str(3)
memory usage: 4.7 KB
None

C:\Users\renzo\AppData\Local\Temp\ipykernel_8544\1283187456.py:3: Pandas4Warning: The inplace keyword in DataFrame.rename is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  data.rename(columns={'Title of your ticket': 'Title', 'Write your ticket': 'Description', 'Your ticket is about': 'About'}, inplace=True)
C:\Users\renzo\AppData\Local\Temp\ipykernel_8544\1283187456.py:4: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  data.drop(columns='Timestamp', inplace=True)

**What we need to do?**

- Check that we have one missing title and one missing ticket content. What we should do? 
- What we can do for the missing Timestamps? 
- Which information we need?
- Always keep in mind our goal.

## Data Processing

In [22]:
data.loc[[72]]
data[data['Title'].isna()]

Empty DataFrame
Columns: [Title, Description, Your ticket is about:]
Index: []

In [ ]:
#Give a title for the ticket

data.loc[72, "Title"] = "The printer doesn't work anymore."

In [15]:
data.loc[[72]]
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  195 non-null    str
 1   Description            194 non-null    str
 2   Your ticket is about:  195 non-null    str
dtypes: str(3)
memory usage: 4.7 KB
None

In [30]:
#What to do with the missing ticket? we delete it from the dataset
data[data['Description'].isna()]
data.iloc[[190]]
data.drop(index=190, inplace=True)

C:\Users\renzo\AppData\Local\Temp\ipykernel_8544\1694084637.py:4: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  data.drop(index=190, inplace=True)

In [76]:
#join the title with the ticket description
data = data.loc[:, ~data.columns.duplicated(keep="first")]
print(data.info())

<class 'pandas.DataFrame'>
Index: 194 entries, 0 to 194
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  194 non-null    str
 1   hallo                  194 non-null    str
 2   Your ticket is about:  194 non-null    str
dtypes: str(3)
memory usage: 10.1 KB
None

In [77]:
print(data.info())
data['ticket about'] = data['Title'] + ' ' + data['hallo']

<class 'pandas.DataFrame'>
Index: 194 entries, 0 to 194
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  194 non-null    str
 1   hallo                  194 non-null    str
 2   Your ticket is about:  194 non-null    str
dtypes: str(3)
memory usage: 10.1 KB
None

In [78]:
data.loc[[72]]
data.info()

<class 'pandas.DataFrame'>
Index: 194 entries, 0 to 194
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  194 non-null    str
 1   hallo                  194 non-null    str
 2   Your ticket is about:  194 non-null    str
 3   ticket about           194 non-null    str
dtypes: str(4)
memory usage: 11.6 KB

In [36]:
#Drop possible columns 
data
data.drop(columns='Timestamp', inplace=True)
print(data.head())

C:\Users\renzo\AppData\Local\Temp\ipykernel_8544\46041803.py:3: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  data.drop(columns='Timestamp', inplace=True)

KeyError: "['Timestamp'] not found in axis"

In [89]:
#rename again the column to: Description
data.rename(columns={'ticket about': 'description','Your ticket is about:': 'about'}, inplace=True)
print(data.info())
print(data.head())

<class 'pandas.DataFrame'>
Index: 194 entries, 0 to 194
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        194 non-null    str
 1   hallo        194 non-null    str
 2   about        194 non-null    str
 3   description  194 non-null    str
dtypes: str(4)
memory usage: 11.6 KB
None
                          Title  \
0  Employee Data Access Request
1      Request for New Monitors
2         Email Client Crashing
3      Slow File-Sharing Server
4  Software License Procurement

                                               hallo                 about  \
0  An employee has requested access to their pers...         Privacy issue
1  We need to purchase 10 new high-resolution mon...  Purchase requisition
2  Our email client is frequently crashing on sta...        Software issue
3  The company's file-sharing server is experienc...        Software issue
4  We need to purchase a new software license for...  Purchase requisition

                                         description
0  Employee Data Access Request An employee has r...
1  Request for New Monitors We need to purchase 1...
2  Email Client Crashing Our email client is freq...
3  Slow File-Sharing Server The company's file-sh...
4  Software License Procurement We need to purcha...

C:\Users\renzo\AppData\Local\Temp\ipykernel_8544\2345153430.py:2: Pandas4Warning: The inplace keyword in DataFrame.rename is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  data.rename(columns={'ticket about': 'description','Your ticket is about:': 'about'}, inplace=True)

In [90]:
print(data.info())
print(data.head())
X = data['description'] 
y = data['about']

<class 'pandas.DataFrame'>
Index: 194 entries, 0 to 194
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        194 non-null    str
 1   hallo        194 non-null    str
 2   about        194 non-null    str
 3   description  194 non-null    str
dtypes: str(4)
memory usage: 11.6 KB
None
                          Title  \
0  Employee Data Access Request
1      Request for New Monitors
2         Email Client Crashing
3      Slow File-Sharing Server
4  Software License Procurement

                                               hallo                 about  \
0  An employee has requested access to their pers...         Privacy issue
1  We need to purchase 10 new high-resolution mon...  Purchase requisition
2  Our email client is frequently crashing on sta...        Software issue
3  The company's file-sharing server is experienc...        Software issue
4  We need to purchase a new software license for...  Purchase requisition

                                         description
0  Employee Data Access Request An employee has r...
1  Request for New Monitors We need to purchase 1...
2  Email Client Crashing Our email client is freq...
3  Slow File-Sharing Server The company's file-sh...
4  Software License Procurement We need to purcha...

Split your data already to be sure that no data likeage will happens

In [91]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state = 4)

In [92]:
train = pd.concat([X_train, y_train], axis =1)
train.to_csv('train_tickets.csv')

In [93]:
test = pd.concat([X_test, y_test], axis =1)
test.to_csv('test_tickets.csv')

In [20]:
train

                                          Description                 Class
56  Laptop Won't Boot. Data is missing from the da...        Software issue
24  New software for front-end developers. The fro...        Software issue
43  Office Software Licenses. Request to purchase ...  Purchase requisition
11  Update issues. In our most recent update many ...        Software issue
41  Access Permission Audit. Conduct a review of u...         Privacy issue
22  Policies for new department . Make policies fo...         Privacy issue
64  Request for Monitor Upgrade. The design team n...  Purchase requisition
18  Java update required. A Java update is require...        Software issue
48  Slow database query. Some standard database qu...        Software issue
12  Deprecated hardware. The entire logistical dep...  Purchase requisition
75  GDPR Compliance Audit. We require a comprehens...         Privacy issue
25  CUDA for CPU use won’t work. For the AI traini...        Software issue
37  PDF formattting issue. Adobe illustrator messe...        Software issue
17  Phising emails. I have received several suspic...         Privacy issue
31  Company Event Face removal. Hello I attended o...         Privacy issue
34  Customer data sync error. Customer changed the...        Software issue
15  Payment verification not sent. Several custome...        Software issue
63  Software License Renewal. The license for our ...  Purchase requisition
28  App suddenly closes. Hello I am getting this w...        Software issue
47  Local Language Selection. We need to be able t...        Software issue
33  Non-Disclosure Agreement. NDA signed with a ha...  Purchase requisition
42  Laptop Procurement. We need to purchase ten ne...  Purchase requisition
40  Employee Data Privacy Concern. An employee has...         Privacy issue
32  Banner deal. We have partnered with NYC's Time...  Purchase requisition
23  What data is stored from the employees. The em...         Privacy issue
61  New Laptops Needed. We need to purchase five n...  Purchase requisition
49  Extra cables for redundancy. For redundancy, w...  Purchase requisition
8   User data found on dark web.. Recently some of...         Privacy issue
30  Data Subject Rights. I would like to opt out o...         Privacy issue
53  Application Error. Our accounting software kee...        Software issue
80  Incident Response Plan Review. Review and upda...         Privacy issue
2   Email Client Crashing. Our email client is fre...        Software issue
78  Vendor Data Handling Assessment. Assess how ou...         Privacy issue
65  Network Cable Installation. We require the ins...  Purchase requisition
73  Access Control Review. Conduct a review of use...         Privacy issue
60  Keyboard Not Responding. The printer driver ne...        Software issue
21  Microsoft Office Word compatibility issues . M...        Software issue
70  Firewall Upgrade. Our current firewall is outd...  Purchase requisition
0   Employee Data Access Request. An employee has ...         Privacy issue
3   Slow File-Sharing Server. The company's file-s...        Software issue
52  Update Privacy Policy. Our Privacy Policy ment...         Privacy issue
38  The russians did it again. People who sign up ...         Privacy issue
44  Email Configuration Problem. Some employees ar...        Software issue
74  Privacy Training Request. We need to organize ...         Privacy issue
36  not so "ergonomic" chairs. After a recent poll...  Purchase requisition
57  Software Update Problems. Requesting an update...        Software issue
71  Data Breach Report. We suspect a data breach i...         Privacy issue
79  Privacy Impact Assessment. Conduct a Privacy I...         Privacy issue
58  Monitor Display Issue. Our email client is not...        Software issue
9   Changes to privacy law. Due to a recent change...         Privacy issue
50  Server room Air Conditioning. The Server room ...  Purchase requisition
72  Concern about privacy. An employee has raised ...         Privacy issue
1   Request for New Monitors. We need to purchase ...  Purchase requisition
69  IT Training Request. Requesting training sessi...  Purchase requisition
55  nan. The network appears to be slow, causing d...        Software issue
46  New Users. Our company welcoming some new memb...  Purchase requisition

In [94]:
X_train[0]

'Employee Data Access Request An employee has requested access to their personal data stored in our systems. Please provide them with the requested information in compliance with data '

Well... 

Now start the data processing using NLP techniques!

We need to get some tools to help us.

We will continue in the tickets_classification2 notebook.